name: Docs

on:
  push:
    branches:
    - main
    - 'releases/**'
  pull_request:

jobs:
  build-docs:
    runs-on: 'ubuntu-latest'
    name: Sphinx
    
    env:
      BUILD_TYPE: RELEASE

    steps:
    - uses: actions/checkout@v2

    - name: Install
      working-directory: ${{ github.workspace }}/docs
      run: |
        sudo pip3 install -r requirements.txt

    - name: Mkdir
      run: mkdir -p ${{ github.workspace }}/build

    - name: Sphinx
      working-directory: ${{ github.workspace }}/build
      run: sphinx-build -W ${{ github.workspace }}/docs ${{ github.workspace }}/build/html

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: build/html
