name: Docs

on:
  push:
    branches:
    - main
    - 'releases/**'
  pull_request:

jobs:
  build-docs:
    runs-on: 'ubuntu-latest'
    name: Sphinx
    
    env:
      BUILD_TYPE: RELEASE

    steps:
    - uses: actions/checkout@v2

    - name: apt-get
      run: |
        sudo apt-get install doxygen

    - name: pip
      run: |
        sudo pip3 install -r docs/requirements.txt

    - name: Sphinx
      run: sphinx-build -W ${{ github.workspace }}/docs ${{ github.workspace }}/build

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: build
