name: Tidy

on:
  push:
    branches:
    - main
    - 'releases/**'
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    env:
      BUILD_TYPE: RELEASE
      RUN_CLANG_TIDY: run-clang-tidy

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON

    - name: Tidy
      run: py ${{ env.RUN_CLANG_TIDY }} -p ${{ github.workspace }}/build
