name: Tidy

on:
  push:
    branches:
    - main
    - 'releases/**'
  pull_request:

jobs:
  clang-tidy:
    runs-on: 'ubuntu-latest'
    name: Tidy

    env:
      CXX: clang++
      BUILD_TYPE: RELEASE
      CLANG_TIDY: clang-tidy-11

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: sudo apt-get install -y ${{ env.CLANG_TIDY }}

    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON

    - name: Tidy
      run: |
        for file in ${{ github.workspace }}/source/*.cpp ; do
          ${{ env.CLANG_TIDY }} --quiet -p ${{ github.workspace }}/build ${file}
        done
